services:
  opensearch:
    build:
      context: ./opensearch
      args:
        - OPENSEARCH_U=${OPENSEARCH_USERNAME}
        - OPENSEARCH_P=${OPENSEARCH_PASSWORD}
    container_name: opensearch
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "-u", "${OPENSEARCH_USERNAME}:${OPENSEARCH_PASSWORD}", "https://localhost:9200"]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
        - opensearch-net
    env_file:
    - .secrets